name: petrol_ledger
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.6.7
  linked_scroll_controller: ^0.2.0
  material_symbols_icons: ^4.39.5
  meta: ^1.10.0
  path: ^1.8.2
  path_provider: ^2.0.15
  permission_handler: ^10.2.0
  provider: ^6.0.5
  sqflite: ^2.2.8+2
  tuple: ^2.0.1
  auto_size_text: ^3.0.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.4
  rxdart: ^0.27.7
  intl: ^0.19.0
  csv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  build_web_compilers: ^3.2.7
  mockito: ^5.4.0
  sqflite_common_ffi: ^2.3.3
  

flutter:
  uses-material-design: true
  fonts:
    - family: anonymous pro
      fonts:
        - asset: assets/fonts/anonymous-pro.ttf
    - family: wix
      fonts:
        - asset: assets/fonts/wix.ttf
